// <auto-generated />
using System;
using Fikra.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fikra.DAL.Migrations
{
    [DbContext(typeof(FikraContext))]
    [Migration("20190526075417_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fikra.Model.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<Guid?>("TaskId");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Dashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Effort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Completed");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<double>("Estimated");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<double>("Remaining");

                    b.HasKey("Id");

                    b.ToTable("Efforts");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int?>("DashboardId");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int?>("DashboardId");

                    b.Property<DateTime?>("Due");

                    b.Property<Guid?>("EffortId");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<int>("Priority");

                    b.Property<int?>("ProjectId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.HasIndex("EffortId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Comment", b =>
                {
                    b.HasOne("Fikra.Model.Entities.Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Project", b =>
                {
                    b.HasOne("Fikra.Model.Entities.Dashboard")
                        .WithMany("Projects")
                        .HasForeignKey("DashboardId");
                });

            modelBuilder.Entity("Fikra.Model.Entities.Task", b =>
                {
                    b.HasOne("Fikra.Model.Entities.Dashboard")
                        .WithMany("Tasks")
                        .HasForeignKey("DashboardId");

                    b.HasOne("Fikra.Model.Entities.Effort", "Effort")
                        .WithMany()
                        .HasForeignKey("EffortId");

                    b.HasOne("Fikra.Model.Entities.Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
